  global:
    scrape_interval: 15s
  scrape_configs:
  # Cassandra config
    - job_name: 'cassandra'
      scrape_interval: 15s
      static_configs:
        - targets: ['node0:9500', 'node1:9500', 'node2:9500']